# Use an official Node runtime as a base image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY frontend/app/package*.json ./

# Install dependencies
RUN npm install

# Copy the remaining app source code to the working directory
COPY frontend/app .
RUN ls -ltr
# Expose the port your app runs on
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
